### ISSUE TITLE
Windowed mode

### ISSUE THREAD

**Issue by lpzantony** [fhorinek/adbmirror#1]
Hello, 

First thank you for this amazing piece of software. I was looking for a fast and fluid way to stream my phone screen to my PC. For the record, i'm using Manjaro an arch linux based distro.

I have to issue two address here : 

How do you configure your software to run into windowed mode? In my case, the app takes the whole screen of the computer. I have to close the app to interract with the rest of my OS. I saw in your demo video that it is possible.

Can you adjust the video quality? I think the video quality is 'ok', but I wonder if I can set options when launching your software to tune the resolution?

Thank you in advance for your help,

Regards

LA

**Comment by lpzantony** [comment]
Oh ok, I found  it by myself.

I just had to edit the beginning of start.sh script to change the resolution.

For the fullscreen issue, I had to change the line 67 of guy.py, replacing:
`pygame.FULLSCREEN | pygame.HWSURFACE`
 by
`pygame.RESIZABLE`

See : [pygame documentation](https://www.pygame.org/docs/ref/display.html#pygame.display.set_mode)

Thank's for your job anyway !

**Comment by fhorinek** [comment]
Correct! :)
You can also play with the quality settings in
adbmirror/capclient.py:23 
`args = "-P %ux%u@%ux%u/0 -S -Q `**80**`" % (dev_max, dev_max, disp_max, disp_max)`

**Comment by lpzantony** [comment]
Good to know ! Thanks
