### ISSUE TITLE
cannot start invalid literal for int()

### ISSUE THREAD

**Issue by clues4me** [fhorinek/adbmirror#10]
Here log after command execute :  
* Waiting for device
 * Getting device info
 * Uploading binaries
/data/local/tmp/adbmirror/adbmirror/: ...ped. 3.6 MB/s (410176 bytes in 0.110s)
 * Forwarding ports
 * Staring GUI
Traceback (most recent call last):
  File "gui.py", line 300, in <module>
    a = Main()
  File "gui.py", line 24, in __init__
    orig = map(int, sys.argv[2].split("x"))
ValueError: invalid literal for int() with base 10: 'not'
 * Cleaning up
 please help

**Comment by fhorinek** [comment]
echo the parameters $disp_size $dev_size $dev_dir before starting the guy.py
