### ISSUE TITLE
After quitting didn't restore display settings

### ISSUE THREAD

**Issue by LightTemplar** [fhorinek/adbmirror#2]
I tried it on KDE Neon (it's Ubuntu 16.04 x64  with the last KDE basically) with two displays. It showed phone screen on both displays for a minute, then after I moved mouse, it quit and didn't restore display settings. Moreover, now I can't find a settings for my second monitor and it always mirrors the main monitor. 
What did it change, how can I restore my old display configuration?

**Comment by LightTemplar** [comment]
Ok, my settings I have restored. But the rest remains.

**Comment by fhorinek** [comment]
you can set it up to use windowed mode 
more info here https://github.com/fhorinek/adbmirror/issues/1

**Comment by LightTemplar** [comment]
Thanks! This solves my problem!
