### ISSUE TITLE
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred

### ISSUE THREAD

**Issue by pete111** [fhorinek/adbmirror#4]
Hi there, 
I got 2 error messages while running start.sh:
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred

It seems it have something to do with sound. I don't need sound. 
How could I completely turn off sound transmission via USB in your script please?

**Comment by fhorinek** [comment]
Adbmirror does not do anything with sound.
