### ISSUE TITLE
Pi3 with Note8 / Note4 / MateS

### ISSUE THREAD

**Issue by Vitalic66** [fhorinek/adbmirror#5]
Hi,

I tried to get it to work but facing this error:

`
pi@raspberrypi:~ $ adb*/adb*/start.sh
 * Waiting for device
 * Getting device info
 * Uploading binaries
cp: der Aufruf von stat für 'bin/minicap/arm64-v8a/minicap' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'bin/minicap-shared/android-25/arm64-v8a/minicap.so' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
cp: der Aufruf von stat für 'bin/minitouch/arm64-v8a/minitouch' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
adb: warning: skipping empty directory '/tmp/adbmirror/'
/data/local/tmp/adbmirror/adbmirror/: 0 files pushed. 1 file skipped.
 * Forwarding ports
 * Staring GUI
python: can't open file 'gui.py': [Errno 2] No such file or directory
 * Cleaning up
`

**Comment by Vitalic66** [comment]
Found mistake for MateS. Had to make start.sh executeable. This works now.

Note 8 doesn't work. Android 7.1 unrooted.

**Comment by fhorinek** [comment]
You also need to start the script inside the directory containing bin folde

**Comment by Vitalic66** [comment]
The bin folder is in the same folder.
With Note8 i get this output:

 * Waiting for device
 * Getting device info
 * Uploading binaries
/data/local/tmp/adbmirror/adbmirror/: 3 files p...les skipped. 11.8 MB/s (629080 bytes in 0.051s)
 * Forwarding ports
 * Staring GUI
Traceback (most recent call last):
  File "gui.py", line 300, in <module>
    a = Main()
  File "gui.py", line 22, in __init__
    assert len(sys.argv) == 4
AssertionError
 * Cleaning up

**Comment by fhorinek** [comment]
This time you run it from different directory, anyway check $disp_size $dev_size $dev_dir parameters in start.sh

**Comment by Vitalic66** [comment]
Thanks for the advise. I set dev_size to 1080x2220 like adb shell wm size told and disp_size to 800x480 (6.5" display of pi).

That works for Note8. Looks a little bit nasty on homescreen (too small). Bit better in landscape.

Is there a way to only output content on the pi? So phone display turns off when displayed on pi? 

Any idea why multitouch does not work? Got a 10 point capacitive touch panel on top of the display.

**Comment by fhorinek** [comment]
> Is there a way to only output content on the pi? So phone display turns off when displayed on pi?

not AFAIK

> Any idea why multitouch does not work? Got a 10 point capacitive touch panel on top of the display.

It supports only single touch
