### ISSUE TITLE
How do I achieve this on Windows 7

### ISSUE THREAD

**Issue by SekharMohan** [fhorinek/adbmirror#7]
I tried to run the script on windows 7 but I am not able to run it successfully.  Please find the error log below,

/system/bin/sh: D:/Public/Git/Git/data/local/tmp/adbmirror//minicap: not found
/system/bin/sh: D:/Public/Git/Git/data/local/tmp/adbmirror//minitouch: not found

Please do the needful on this.

**Comment by fhorinek** [comment]
This was never intended to run on windows.

But I guess that you are missing some binaries

**Comment by SekharMohan** [comment]
any workaround to run on windows?

**Comment by fhorinek** [comment]
I do not know, I do not use windows.
You are on your own
