### ISSUE TITLE
How to send touch , click events to device

### ISSUE THREAD

**Issue by djcm75** [fhorinek/adbmirror#9]
Hi,
I would like to use this app to test gaming apks. I can record events using adb shell getevent, how do pass this file as input to adbmirror ?
Thanks
Dexter

**Comment by fhorinek** [comment]
Just write decoder for the file format and pass it somewhere in the gui.py
or touchclient.py
--
František Horínek


ut 12. 6. 2018 o 13:28 djcm75 <notifications@github.com> napísal(a):

**Comment by djcm75** [comment]
Hi Thanks for your quick response,
instead of using adb shell getevent, is it possible to capture and record events on the phone using minitouch and then replay it back

Thanks
Dexter

**Comment by fhorinek** [comment]
No minitouch can only send touches afaik
